# Generated by Django 5.0.6 on 2024-09-11 12:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QualityForm",
            fields=[
                (
                    "reference_test",
                    models.IntegerField(default=0, primary_key=True, serialize=False),
                ),
                ("date_test", models.CharField(default="", max_length=150)),
                (
                    "status_test",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("time_test", models.CharField(blank=True, default="", max_length=150)),
                ("dose", models.CharField(blank=True, default="", max_length=150)),
                ("is_edit", models.BooleanField(default=False)),
                ("is_finish", models.BooleanField(default=False)),
                (
                    "json_field",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(blank=True, null=True),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("strain", models.CharField(default="new", max_length=150)),
                ("fruit", models.CharField(blank=True, default="", max_length=150)),
            ],
        ),
    ]
